package com.krivi.apihistorialmedico.model.importacion;

public enum PacienteImportacionErrorCodigo {
  ARCHIVO_VACIO,
  ARCHIVO_DEMASIADO_GRANDE,
  FORMATO_NO_PERMITIDO,
  ARCHIVO_CORRUPTO,
  PLANTILLA_NO_RECONOCIDA,
  VERSION_INCOMPATIBLE,
  HOJA_PRINCIPAL_FALTANTE,
  COLUMNA_FALTANTE,
  ENCABEZADO_DUPLICADO,
  MAX_REGISTROS_EXCEDIDO,
  FORMULA_NO_PERMITIDA,
  CAMPO_OBLIGATORIO,
  DNI_INVALIDO,
  DNI_EXISTENTE,
  DNI_DUPLICADO_ARCHIVO,
  FECHA_INVALIDA,
  FECHA_FUTURA,
  SEXO_INVALIDO,
  ESTADO_CIVIL_INVALIDO,
  EDUCACION_INVALIDA,
  IMPORTACION_NO_ENCONTRADA,
  IMPORTACION_EXPIRADA,
  IMPORTACION_YA_CONFIRMADA,
  IMPORTACION_NO_AUTORIZADA
}
