-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 20:44:42 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema historiaclinicadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema historiaclinicadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `historiaclinicadb` DEFAULT CHARACTER SET utf8 ;
USE `historiaclinicadb` ;

-- -----------------------------------------------------
-- Table `historiaclinicadb`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`paciente` (
  `idpaciente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(120) NULL,
  `apellidos` VARCHAR(120) NULL,
  `fechaingreso` DATE NULL,
  `fechanacimiento` DATE NULL,
  `estadocivil` VARCHAR(45) NULL,
  `numdocumento` VARCHAR(15) NULL,
  `sexo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  `traidopor` VARCHAR(45) NULL,
  PRIMARY KEY (`idpaciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`antecedentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`antecedentes` (
  `idantecedentes` INT NOT NULL AUTO_INCREMENT,
  `alimentacion` VARCHAR(120) NULL,
  `habitos` VARCHAR(120) NULL,
  `vivienda` VARCHAR(120) NULL,
  `desarrollopsicomotor` VARCHAR(120) NULL,
  `vacunas` VARCHAR(120) NULL,
  `educacion` VARCHAR(120) NULL,
  `enfermedadesprevias` VARCHAR(120) NULL,
  `cirugiasprevias` VARCHAR(120) NULL,
  `alergiamedicamentos` VARCHAR(120) NULL,
  `idpaciente` INT NOT NULL,
  PRIMARY KEY (`idantecedentes`),
  INDEX `fk_antecedentes_paciente1_idx` (`idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_antecedentes_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `historiaclinicadb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `historiaclinicadb`.`historiaclinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`historiaclinica` (
  `idhistoriaclinica` INT NOT NULL AUTO_INCREMENT,
  `fechacreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ultimaactualizacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `idpaciente` INT NOT NULL,
  PRIMARY KEY (`idhistoriaclinica`),
  UNIQUE INDEX `uk_historiaclinica_paciente` (`idpaciente` ASC) VISIBLE,
  CONSTRAINT `fk_historiaclinica_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `historiaclinicadb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `historiaclinicadb`.`tipoenfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`tipoenfermedad` (
  `idtipoenfermedad` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`idtipoenfermedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `tipodocumento` VARCHAR(65) NULL,
  `numdocumento` VARCHAR(15) NULL,
  `nombres` VARCHAR(125) NULL,
  `apellidos` VARCHAR(125) NULL,
  `direccion` VARCHAR(125) NULL,
  `telefono` VARCHAR(15) NULL,
  `celular` VARCHAR(15) NULL,
  `cargo` VARCHAR(65) NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `tipousuario` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `idempleado` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `historiaclinicadb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`consulta` (
  `idconsulta` INT NOT NULL AUTO_INCREMENT,
  `presionarterial` VARCHAR(120) NULL,
  `frecuenciacardiaca` VARCHAR(45) NULL,
  `fecuenciarespiratoria` VARCHAR(45) NULL,
  `talla` VARCHAR(45) NULL,
  `temperatura` VARCHAR(45) NULL,
  `peso` DECIMAL(7,2) NULL,
  `fechaconsulta` DATE NULL,
  `tiempoenfermedad` VARCHAR(45) NULL,
  `idtipoenfermedad` INT NOT NULL,
  `relatopaciente` VARCHAR(250) NULL,
  `idpaciente` INT NOT NULL,
  `idusuario` INT NULL,
  `idhistoriaclinica` INT NULL,
  `idempleado` INT NULL,
  `especialidadrequerida` VARCHAR(80) NULL,
  `diagnostico` VARCHAR(250) NULL,
  `examenesrecetados` VARCHAR(250) NULL,
  `receta` VARCHAR(250) NULL,
  `tratamiento` VARCHAR(250) NULL,
  `proximacita` DATE NULL,
  `fechacreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` VARCHAR(45) NOT NULL DEFAULT 'PENDIENTE',
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_tipoenferdad_idx` (`idtipoenfermedad` ASC) VISIBLE,
  INDEX `fk_consulta_paciente1_idx` (`idpaciente` ASC) VISIBLE,
  INDEX `fk_consulta_usuario1_idx` (`idusuario` ASC) VISIBLE,
  INDEX `fk_consulta_historiaclinica1_idx` (`idhistoriaclinica` ASC) VISIBLE,
  INDEX `fk_consulta_empleado1_idx` (`idempleado` ASC) VISIBLE,
  CONSTRAINT `fk_consulta_tipoenferdad`
    FOREIGN KEY (`idtipoenfermedad`)
    REFERENCES `historiaclinicadb`.`tipoenfermedad` (`idtipoenfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`idpaciente`)
    REFERENCES `historiaclinicadb`.`paciente` (`idpaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `historiaclinicadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_historiaclinica1`
    FOREIGN KEY (`idhistoriaclinica`)
    REFERENCES `historiaclinicadb`.`historiaclinica` (`idhistoriaclinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `historiaclinicadb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ruta` VARCHAR(150) NULL,
  `imagen` VARCHAR(150) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`detallepermiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`detallepermiso` (
  `iddetallepermiso` INT NOT NULL AUTO_INCREMENT,
  `idmenu` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`iddetallepermiso`),
  INDEX `fk_detallepermiso_menu1_idx` (`idmenu` ASC) VISIBLE,
  INDEX `fk_detallepermiso_usuario1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_detallepermiso_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `historiaclinicadb`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallepermiso_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `historiaclinicadb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_historiaclinica1`
    FOREIGN KEY (`idhistoriaclinica`)
    REFERENCES `historiaclinicadb`.`historiaclinica` (`idhistoriaclinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_empleado1`
    FOREIGN KEY (`idempleado`)
    REFERENCES `historiaclinicadb`.`empleado` (`idempleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `historiaclinicadb`.`submenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historiaclinicadb`.`submenu` (
  `idsubmenu` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `ruta` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `idmenu` INT NOT NULL,
  PRIMARY KEY (`idsubmenu`),
  INDEX `fk_submenu_menu1_idx` (`idmenu` ASC) VISIBLE,
  CONSTRAINT `fk_submenu_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `historiaclinicadb`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Catálogo inicial normalizado de tipos generales de enfermedad para consultas médicas.
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'RESPIRATORIA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'RESPIRATORIA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'DIGESTIVA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'DIGESTIVA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'CARDIOVASCULAR' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'CARDIOVASCULAR');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'NEUROLOGICA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'NEUROLOGICA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'DERMATOLOGICA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'DERMATOLOGICA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'MUSCULOESQUELETICA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'MUSCULOESQUELETICA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'INFECCIOSA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'INFECCIOSA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'ALERGICA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'ALERGICA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'URINARIA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'URINARIA');
INSERT INTO `historiaclinicadb`.`tipoenfermedad` (`descripcion`)
SELECT 'OTRA' WHERE NOT EXISTS (SELECT 1 FROM `historiaclinicadb`.`tipoenfermedad` WHERE `descripcion` = 'OTRA');

-- Normalización de valores históricos de estado civil.
UPDATE `historiaclinicadb`.`paciente`
SET `estadocivil` = CASE
  WHEN UPPER(TRIM(`estadocivil`)) IN ('SOLTERO', 'SOLTERA', 'SOLTERO(A)') THEN 'SOLTERO'
  WHEN UPPER(TRIM(`estadocivil`)) IN ('CASADO', 'CASADA', 'CASADO(A)') THEN 'CASADO'
  WHEN UPPER(TRIM(`estadocivil`)) IN ('DIVORCIADO', 'DIVORCIADA', 'DIVORCIADO(A)') THEN 'DIVORCIADO'
  WHEN UPPER(TRIM(`estadocivil`)) IN ('VIUDO', 'VIUDA', 'VIUDO(A)') THEN 'VIUDO'
  ELSE UPPER(TRIM(`estadocivil`))
END
WHERE `estadocivil` IS NOT NULL;

-- Migración para bases existentes: agregar columnas faltantes de Consulta si la tabla ya existe.
-- Ejecutar manualmente solo si la tabla `consulta` fue creada antes de estos cambios.
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `idhistoriaclinica` INT NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `idempleado` INT NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `especialidadrequerida` VARCHAR(80) NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `diagnostico` VARCHAR(250) NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `examenesrecetados` VARCHAR(250) NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `receta` VARCHAR(250) NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `tratamiento` VARCHAR(250) NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `proximacita` DATE NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `fechacreacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD COLUMN `estado` VARCHAR(45) NOT NULL DEFAULT 'PENDIENTE';
-- ALTER TABLE `historiaclinicadb`.`consulta` MODIFY COLUMN `idusuario` INT NULL;
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD CONSTRAINT `fk_consulta_historiaclinica1` FOREIGN KEY (`idhistoriaclinica`) REFERENCES `historiaclinicadb`.`historiaclinica` (`idhistoriaclinica`);
-- ALTER TABLE `historiaclinicadb`.`consulta` ADD CONSTRAINT `fk_consulta_empleado1` FOREIGN KEY (`idempleado`) REFERENCES `historiaclinicadb`.`empleado` (`idempleado`);
